---

# install and configure Bind9


# fail if it's not a Debian based system
- name: Check OS (bind9)
  fail: msg="Not a Debian based system!"
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'


- name: Installation for Debian like systems
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
